apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "-90"      # before everything that uses ExternalSecret
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.5
      helm:
        valueFiles:
          - $values/helm-values/external-secrets-values.yaml
    - repoURL: https://github.com/reonbritto/sbom-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
