apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "-35"     # before tempo + mimir (loki creates obs-sa)
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.18.0
      helm:
        valueFiles:
          - $values/helm-values/loki-values.yaml
    - repoURL: https://github.com/reonbritto/sbom-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
