apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.108.0
      helm:
        valueFiles:
          - $values/helm-values/opentelemetry-collector-values.yaml
    - repoURL: https://github.com/reonbritto/sbom-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
