# External Secrets Operator Helm values
# Chart: external-secrets/external-secrets

installCRDs: true
replicaCount: 1

serviceAccount:
  create: true
  name: eso-service-account
  annotations:
    azure.workload.identity/client-id: "__ESO_MI_CLIENT_ID__"
    azure.workload.identity/tenant-id: "__TENANT_ID__"

podLabels:
  azure.workload.identity/use: "true"

webhook:
  podLabels:
    azure.workload.identity/use: "true"

certController:
  podLabels:
    azure.workload.identity/use: "true"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceMonitor:
  enabled: true
