# External Secrets Operator Helm values
# Chart: external-secrets/external-secrets

installCRDs: true
replicaCount: 1

serviceAccount:
  create: true
  name: eso-service-account
  annotations:
    azure.workload.identity/client-id: "7e99f72f-81f8-424d-b866-68b709470e1b"
    azure.workload.identity/tenant-id: "d1d16433-e375-4076-a7ea-c57bb79df0de"

podLabels:
  azure.workload.identity/use: "true"

webhook:
  podLabels:
    azure.workload.identity/use: "true"

certController:
  podLabels:
    azure.workload.identity/use: "true"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceMonitor:
  enabled: true
